import Ember from 'ember';

var CurrencyController = Ember.ArrayController.extend({

  inputValue: '',

  firstSelectOptions: [    
    {value: '', label: 'Select Currency 1'},
    {value: "WST", label: 'Samoan tala'},
    {value: "BTN", label: 'Bhutanese ngultrum'},
    {value: "PGK", label: 'Papua New Guinean kina'},
    {value: "AMD", label: 'Armenian dram'},
    {value: "CVE", label: 'Cape Verdean escudo'},
    {value: "LYD", label: 'Libyan dinar'},
    {value: "RWF", label: 'Rwandan franc'},
    {value: "GEL", label: 'Georgian lari'},
    {value: "ERN", label: 'Eritrean nakfa'},
    {value: "KWD", label: 'Kuwaiti dinar'},
    {value: "BHD", label: 'Bahraini dinar'},
    {value: "HTG", label: 'Haitian gourde'},
    {value: "MZM", label: 'Mozambican metical'},
    {value: "JOD", label: 'Jordanian dinar'},
    {value: "MRO", label: 'Mauritanian ouguiya'},
    {value: "SLL", label: 'Sierra Leonean leone'},
    {value: "MWK", label: 'Malawian kwacha'},
    {value: "XPF", label: 'CFP franc'},
    {value: "RSD", label: 'Serbian dinar Дин.'},
    {value: "OMR", label: 'Omani ria ,﷼l'},
    {value: "CRC", label: 'Costa Rican colo ,₡n'},
    {value: "MNT", label: 'Mongolian tugri ,₮k'},
    {value: "NGN", label: 'Nigerian nair ,₦a'},
    {value: "STD", label: 'Sao Tome and Principe dobra'},
    {value: "AOA", label: 'Angolan kwanza'},
    {value: "BIF", label: 'Burundi franc'},
    {value: "LSL", label: 'Lesotho loti'},
    {value: "MMK", label: 'Myanma kyat'},
    {value: "TOP", label: 'Paanga'},
    {value: "VEB", label: 'Venezuelan bolivar'},
    {value: "DZD", label: 'Algerian dinar'},
    {value: "CDF", label: 'Congolese franc'},
    {value: "GQE", label: 'Central African CFA franc'},
    {value: "GMD", label: 'Gambian dalasi'},
    {value: "IQD", label: 'Iraqi dinar'},
    {value: "MGA", label: 'Malagasy ariary'},
    {value: "MDL", label: 'Moldovan leu'},
    {value: "MAD", label: 'Moroccan dirham'},
    {value: "TRY", label: 'Turkish new lira'},
    {value: "AED", label: 'UAE dirham'},
    {value: "VUV", label: 'Vanuatu vatu'},
    {value: "BDT", label: 'Bangladeshi taka'},
    {value: "ETB", label: 'Ethiopian birr'},
    {value: "KMF", label: 'Comorian franc'},
    {value: "MVR", label: 'Maldivian rufiyaa'},
    {value: "SZL", label: 'Swazi lilangeni'},
    {value: "DJF", label: 'Djiboutian franc'},
    {value: "GNF", label: 'Guinean franc'},
    {value: "GHS", label: 'Ghanaian cedi'},
    {value: "ZMK", label: 'Zambian kwacha'},
    {value: "XDR", label: 'Special Drawing Rights'},
    {value: "MOP", label: 'Macanese pataca'},
    {value: "TJS", label: 'Tajikistani somoni'},
    {value: "TND", label: 'Tunisian dinar'},
    {value: "TMM", label: 'Turkmen manat'},
    {value: "XOF", label: 'West African CFA franc'},
    {value: "XAF", label: 'Central African CFA franc'},
    {value: "XCD", label: 'East Caribbean dollar $'},
    {value: "SDG", label: 'Sudanese pound'},
    {value: "ALL", label: 'Albanian lek Lek'},
    {value: "BBD", label: 'Barbadian dollar $'},
    {value: "BND", label: 'Brunei dollar $'},
    {value: "HUF", label: 'Hungarian forint Ft'},
    {value: "JMD", label: 'Jamaican dolla ,J$r'},
    {value: "AUD", label: 'Australian dollar $'},
    {value: "GIP", label: 'Gibraltar pound ,£d'},
    {value: "NZD", label: 'New Zealand dollar $'},
    {value: "FKP", label: 'Falkland Islands pound ,£d'},
    {value: "MKD", label: 'Macedonian denar ден'},
    {value: "INR", label: 'Indian rupe ,₹e'},
    {value: "TZS", label: 'Tanzanian shilling TSh'},
    {value: "BAM", label: 'Bosnia and Herzegovina konvertibilna marka KM'},
    {value: "SEK", label: 'Swedish krona kr'},
    {value: "CNY", label: 'Chinese renminb ,¥i'},
    {value: "BSD", label: 'Bahamian dollar $'},
    {value: "BWP", label: 'Botswana pul ,Pa'},
    {value: "LAK", label: 'Lao ki ,₭p'},
    {value: "SYP", label: 'Syrian pound ,£d'},
    {value: "CZK", label: 'Czech koruna Kč'},
    {value: "ANG", label: 'Netherlands Antillean gulde ,ƒn'},
    {value: "KRW", label: 'South Korean wo ,₩n'},
    {value: "GTQ", label: 'Guatemalan quetza ,Ql'},
    {value: "SOS", label: 'Somali shillin ,Sg'},
    {value: "DKK", label: 'Danish krone kr'},
    {value: "PEN", label: 'Peruvian nuevo so ,S/.l'},
    {value: "COP", label: 'Colombian peso $'},
    {value: "LBP", label: 'Lebanese lir ,£a'},
    {value: "QAR", label: 'Qatari riya ,﷼l'},
    {value: "BZD", label: 'Belize dollar BZ$'},
    {value: "KZT", label: 'Kazakhstani tenge лв'},
    {value: "MUR", label: 'Mauritian rupe ,₨e'},
    {value: "AWG", label: 'Aruban flori ,ƒn'},
    {value: "KYD", label: 'Cayman Islands dollar $'},
    {value: "IDR", label: 'Indonesian rupiah Rp'},
    {value: "EUR", label: 'European Eur ,€o'},
    {value: "IRR", label: 'Iranian ria ,﷼l'},
    {value: "ILS", label: 'Israeli new sheqe ,₪l'},
    {value: "MYR", label: 'Malaysian ringgit RM'},
    {value: "HNL", label: 'Honduran lempir ,La'},
    {value: "PAB", label: 'Panamanian balbo ,B/.a'},
    {value: "PHP", label: 'Philippine pes ,₱o'},
    {value: "ZAR", label: 'South African ran ,Rd'},
    {value: "SAR", label: 'Saudi riya ,﷼l'},
    {value: "SGD", label: 'Singapore dollar $'},
    {value: "RON", label: 'Romanian leu lei'},
    {value: "SRD", label: 'Surinamese dollar $'},
    {value: "TWD", label: 'New Taiwan dollar NT$'},
    {value: "ARS", label: 'Argentine peso $'},
    {value: "AZN", label: 'Azerbaijani manat ман'},
    {value: "BYR", label: 'Belarusian rubl ,p.e'},
    {value: "BGN", label: 'Bulgarian lev лв'},
    {value: "BOB", label: 'Bolivian boliviano $b'},
    {value: "CAD", label: 'Canadian dollar $'},
    {value: "CLP", label: 'Chilean peso $'},
    {value: "DOP", label: 'Dominican peso RD$'},
    {value: "FJD", label: 'Fijian dollar $'},
    {value: "GYD", label: 'Guyanese dollar $'},
    {value: "ISK", label: 'Icelandic króna kr'},
    {value: "JPY", label: 'Japanese ye ,¥n'},
    {value: "KPW", label: 'North Korean wo ,₩n'},
    {value: "LVL", label: 'Latvian lats Ls'},
    {value: "CHF", label: 'Swiss franc Fr.'},
    {value: "NPR", label: 'Nepalese rupe ,₨e'},
    {value: "NIO", label: 'Nicaraguan cordob ,C$a'},
    {value: "PKR", label: 'Pakistani rupe ,₨e'},
    {value: "PYG", label: 'Paraguayan guarani Gs'},
    {value: "SHP", label: 'Saint Helena pound ,£d'},
    {value: "SBD", label: 'Solomon Islands dollar $'},
    {value: "LKR", label: 'Sri Lankan rupe ,₨e'},
    {value: "YER", label: 'Yemeni ria ,﷼l'},
    {value: "TTD", label: 'Trinidad and Tobago dollar TT$'},
    {value: "BRL", label: 'Brazilian rea ,R$l'},
    {value: "HRK", label: 'Croatian kuna kn'},
    {value: "SCR", label: 'Seychellois rupe ,₨e'},
    {value: "THB", label: 'Thai bah ,฿t'},
    {value: "AFN", label: 'Afghan afghan ,؋i'},
    {value: "NOK", label: 'Norwegian krone kr'},
    {value: "KHR", label: 'Cambodian rie ,៛l'},
    {value: "EGP", label: 'Egyptian pound ,£d'},
    {value: "HKD", label: 'Hong Kong dollar $'},
    {value: "LRD", label: 'Liberian dollar $'},
    {value: "NAD", label: 'Namibian dollar $'},
    {value: "RUB", label: 'Russian ruble руб'},
    {value: "KGS", label: 'Kyrgyzstani som лв'},
    {value: "PLN", label: 'Polish zloty zł'},
    {value: "UYU", label: 'Uruguayan peso $U'},
    {value: "VND", label: 'Vietnamese don ,₫g'},
    {value: "KES", label: 'Kenyan shilling KSh'},
    {value: "MXN", label: 'Mexican peso $'},
    {value: "UGX", label: 'Ugandan shilling USh'},
    {value: "UZS", label: 'Uzbekistani som лв'},
    {value: "UAH", label: 'Ukrainian hryvni ,₴a'},
    {value: "GBP", label: 'British pound ,£d'},
    {value: "USD", label: 'United States dollar $'},
    {value: "CUP", label: 'Cuban peso $'},
    {value: "BTC", label: 'Bitcoin BTC'},
  ],

  secondSelectOptions: [
    {value: '', label: 'Select Currency 2'},
    {value: "WST", label: 'Samoan tala'},
    {value: "BTN", label: 'Bhutanese ngultrum'},
    {value: "PGK", label: 'Papua New Guinean kina'},
    {value: "AMD", label: 'Armenian dram'},
    {value: "CVE", label: 'Cape Verdean escudo'},
    {value: "LYD", label: 'Libyan dinar'},
    {value: "RWF", label: 'Rwandan franc'},
    {value: "GEL", label: 'Georgian lari'},
    {value: "ERN", label: 'Eritrean nakfa'},
    {value: "KWD", label: 'Kuwaiti dinar'},
    {value: "BHD", label: 'Bahraini dinar'},
    {value: "HTG", label: 'Haitian gourde'},
    {value: "MZM", label: 'Mozambican metical'},
    {value: "JOD", label: 'Jordanian dinar'},
    {value: "MRO", label: 'Mauritanian ouguiya'},
    {value: "SLL", label: 'Sierra Leonean leone'},
    {value: "MWK", label: 'Malawian kwacha'},
    {value: "XPF", label: 'CFP franc'},
    {value: "RSD", label: 'Serbian dinar Дин.'},
    {value: "OMR", label: 'Omani ria ,﷼l'},
    {value: "CRC", label: 'Costa Rican colo ,₡n'},
    {value: "MNT", label: 'Mongolian tugri ,₮k'},
    {value: "NGN", label: 'Nigerian nair ,₦a'},
    {value: "STD", label: 'Sao Tome and Principe dobra'},
    {value: "AOA", label: 'Angolan kwanza'},
    {value: "BIF", label: 'Burundi franc'},
    {value: "LSL", label: 'Lesotho loti'},
    {value: "MMK", label: 'Myanma kyat'},
    {value: "TOP", label: 'Paanga'},
    {value: "VEB", label: 'Venezuelan bolivar'},
    {value: "DZD", label: 'Algerian dinar'},
    {value: "CDF", label: 'Congolese franc'},
    {value: "GQE", label: 'Central African CFA franc'},
    {value: "GMD", label: 'Gambian dalasi'},
    {value: "IQD", label: 'Iraqi dinar'},
    {value: "MGA", label: 'Malagasy ariary'},
    {value: "MDL", label: 'Moldovan leu'},
    {value: "MAD", label: 'Moroccan dirham'},
    {value: "TRY", label: 'Turkish new lira'},
    {value: "AED", label: 'UAE dirham'},
    {value: "VUV", label: 'Vanuatu vatu'},
    {value: "BDT", label: 'Bangladeshi taka'},
    {value: "ETB", label: 'Ethiopian birr'},
    {value: "KMF", label: 'Comorian franc'},
    {value: "MVR", label: 'Maldivian rufiyaa'},
    {value: "SZL", label: 'Swazi lilangeni'},
    {value: "DJF", label: 'Djiboutian franc'},
    {value: "GNF", label: 'Guinean franc'},
    {value: "GHS", label: 'Ghanaian cedi'},
    {value: "ZMK", label: 'Zambian kwacha'},
    {value: "XDR", label: 'Special Drawing Rights'},
    {value: "MOP", label: 'Macanese pataca'},
    {value: "TJS", label: 'Tajikistani somoni'},
    {value: "TND", label: 'Tunisian dinar'},
    {value: "TMM", label: 'Turkmen manat'},
    {value: "XOF", label: 'West African CFA franc'},
    {value: "XAF", label: 'Central African CFA franc'},
    {value: "XCD", label: 'East Caribbean dollar $'},
    {value: "SDG", label: 'Sudanese pound'},
    {value: "ALL", label: 'Albanian lek Lek'},
    {value: "BBD", label: 'Barbadian dollar $'},
    {value: "BND", label: 'Brunei dollar $'},
    {value: "HUF", label: 'Hungarian forint Ft'},
    {value: "JMD", label: 'Jamaican dolla ,J$r'},
    {value: "AUD", label: 'Australian dollar $'},
    {value: "GIP", label: 'Gibraltar pound ,£d'},
    {value: "NZD", label: 'New Zealand dollar $'},
    {value: "FKP", label: 'Falkland Islands pound ,£d'},
    {value: "MKD", label: 'Macedonian denar ден'},
    {value: "INR", label: 'Indian rupe ,₹e'},
    {value: "TZS", label: 'Tanzanian shilling TSh'},
    {value: "BAM", label: 'Bosnia and Herzegovina konvertibilna marka KM'},
    {value: "SEK", label: 'Swedish krona kr'},
    {value: "CNY", label: 'Chinese renminb ,¥i'},
    {value: "BSD", label: 'Bahamian dollar $'},
    {value: "BWP", label: 'Botswana pul ,Pa'},
    {value: "LAK", label: 'Lao ki ,₭p'},
    {value: "SYP", label: 'Syrian pound ,£d'},
    {value: "CZK", label: 'Czech koruna Kč'},
    {value: "ANG", label: 'Netherlands Antillean gulde ,ƒn'},
    {value: "KRW", label: 'South Korean wo ,₩n'},
    {value: "GTQ", label: 'Guatemalan quetza ,Ql'},
    {value: "SOS", label: 'Somali shillin ,Sg'},
    {value: "DKK", label: 'Danish krone kr'},
    {value: "PEN", label: 'Peruvian nuevo so ,S/.l'},
    {value: "COP", label: 'Colombian peso $'},
    {value: "LBP", label: 'Lebanese lir ,£a'},
    {value: "QAR", label: 'Qatari riya ,﷼l'},
    {value: "BZD", label: 'Belize dollar BZ$'},
    {value: "KZT", label: 'Kazakhstani tenge лв'},
    {value: "MUR", label: 'Mauritian rupe ,₨e'},
    {value: "AWG", label: 'Aruban flori ,ƒn'},
    {value: "KYD", label: 'Cayman Islands dollar $'},
    {value: "IDR", label: 'Indonesian rupiah Rp'},
    {value: "EUR", label: 'European Eur ,€o'},
    {value: "IRR", label: 'Iranian ria ,﷼l'},
    {value: "ILS", label: 'Israeli new sheqe ,₪l'},
    {value: "MYR", label: 'Malaysian ringgit RM'},
    {value: "HNL", label: 'Honduran lempir ,La'},
    {value: "PAB", label: 'Panamanian balbo ,B/.a'},
    {value: "PHP", label: 'Philippine pes ,₱o'},
    {value: "ZAR", label: 'South African ran ,Rd'},
    {value: "SAR", label: 'Saudi riya ,﷼l'},
    {value: "SGD", label: 'Singapore dollar $'},
    {value: "RON", label: 'Romanian leu lei'},
    {value: "SRD", label: 'Surinamese dollar $'},
    {value: "TWD", label: 'New Taiwan dollar NT$'},
    {value: "ARS", label: 'Argentine peso $'},
    {value: "AZN", label: 'Azerbaijani manat ман'},
    {value: "BYR", label: 'Belarusian rubl ,p.e'},
    {value: "BGN", label: 'Bulgarian lev лв'},
    {value: "BOB", label: 'Bolivian boliviano $b'},
    {value: "CAD", label: 'Canadian dollar $'},
    {value: "CLP", label: 'Chilean peso $'},
    {value: "DOP", label: 'Dominican peso RD$'},
    {value: "FJD", label: 'Fijian dollar $'},
    {value: "GYD", label: 'Guyanese dollar $'},
    {value: "ISK", label: 'Icelandic króna kr'},
    {value: "JPY", label: 'Japanese ye ,¥n'},
    {value: "KPW", label: 'North Korean wo ,₩n'},
    {value: "LVL", label: 'Latvian lats Ls'},
    {value: "CHF", label: 'Swiss franc Fr.'},
    {value: "NPR", label: 'Nepalese rupe ,₨e'},
    {value: "NIO", label: 'Nicaraguan cordob ,C$a'},
    {value: "PKR", label: 'Pakistani rupe ,₨e'},
    {value: "PYG", label: 'Paraguayan guarani Gs'},
    {value: "SHP", label: 'Saint Helena pound ,£d'},
    {value: "SBD", label: 'Solomon Islands dollar $'},
    {value: "LKR", label: 'Sri Lankan rupe ,₨e'},
    {value: "YER", label: 'Yemeni ria ,﷼l'},
    {value: "TTD", label: 'Trinidad and Tobago dollar TT$'},
    {value: "BRL", label: 'Brazilian rea ,R$l'},
    {value: "HRK", label: 'Croatian kuna kn'},
    {value: "SCR", label: 'Seychellois rupe ,₨e'},
    {value: "THB", label: 'Thai bah ,฿t'},
    {value: "AFN", label: 'Afghan afghan ,؋i'},
    {value: "NOK", label: 'Norwegian krone kr'},
    {value: "KHR", label: 'Cambodian rie ,៛l'},
    {value: "EGP", label: 'Egyptian pound ,£d'},
    {value: "HKD", label: 'Hong Kong dollar $'},
    {value: "LRD", label: 'Liberian dollar $'},
    {value: "NAD", label: 'Namibian dollar $'},
    {value: "RUB", label: 'Russian ruble руб'},
    {value: "KGS", label: 'Kyrgyzstani som лв'},
    {value: "PLN", label: 'Polish zloty zł'},
    {value: "UYU", label: 'Uruguayan peso $U'},
    {value: "VND", label: 'Vietnamese don ,₫g'},
    {value: "KES", label: 'Kenyan shilling KSh'},
    {value: "MXN", label: 'Mexican peso $'},
    {value: "UGX", label: 'Ugandan shilling USh'},
    {value: "UZS", label: 'Uzbekistani som лв'},
    {value: "UAH", label: 'Ukrainian hryvni ,₴a'},
    {value: "GBP", label: 'British pound ,£d'},
    {value: "USD", label: 'United States dollar $'},
    {value: "CUP", label: 'Cuban peso $'},
    {value: "BTC", label: 'Bitcoin BTC'},
  ],

  selectedFirstOptionDidChange: function() {
    // var first_option = this.get('selectedFirstOption');
    // var second_option = this.get('selectedSecondOption');
    // this.set('firstInputValue', '');
    this.set('outputValue', '');
  }.observes('selectedFirstOption', 'selectedSecondOption'),

  firstInputValueDidChange: function() {
    var first_option = this.get('selectedFirstOption').value;
    var second_option = this.get('selectedSecondOption').value;
    this.set('inputValue', this.get('firstInputValue'));
    var self = this;
    // https://currencyconverter.p.mashape.com/?from=USD&from_amount=1&to=SEK"
    // var url = 'http://rate-exchange.appspot.com/currency?from=' + first_option + '&to=' + second_option;
    // var url = 'https://currencyconverter.p.mashape.com/?from=' + first_option + '&from_amount=' + this.get('firstInputValue') + '&to=' + second_option
    var url = "http://devel.farebookings.com/api/curconversor/" + first_option + "/" + second_option + "/" + this.get('firstInputValue') + "/";
    Ember.$.ajax({
        url: url,
        jsonp: 'callback',
        dataType: 'jsonp',
      }).then(function(response) {
        var output_value = response[second_option];
        self.set('outputValue', output_value);
      });
    
  }.observes('firstInputValue', 'selectedSecondOption'),

  
});


export default CurrencyController;
